# Generated by Django 5.1.1 on 2024-10-13 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='', verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(default='', verbose_name='Instrucciones'),
        ),
        migrations.AddField(
            model_name='post',
            name='tabla',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Tabla'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
