# Generated by Django 5.1.1 on 2024-10-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRecetas', '0002_remove_post_content_remove_post_excerpt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
